// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package storage

import (
	"database/sql"

	"github.com/google/uuid"
)

type Client struct {
	ID          uuid.UUID
	FullName    string
	PhoneNumber string
	Latitude    float64
	Longitude   float64
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
	DeletedAt   sql.NullInt32
}

type Company struct {
	ID          uuid.UUID
	Name        string
	Description sql.NullString
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
	DeletedAt   sql.NullInt32
}

type Employee struct {
	ID           uuid.UUID
	Username     string
	FullName     string
	PhoneNumber  string
	Role         string
	PasswordHash string
	CreatedAt    sql.NullTime
	UpdatedAt    sql.NullTime
	DeletedAt    sql.NullTime
}

type Order struct {
	ID         uuid.UUID
	ClientID   uuid.UUID
	ServiceID  uuid.UUID
	Area       float64
	TotalPrice float64
	Status     sql.NullString
	CreatedAt  sql.NullTime
	UpdatedAt  sql.NullTime
	DeletedAt  sql.NullInt32
}

type Service struct {
	ID          uuid.UUID
	Tariffs     sql.NullString
	Name        string
	Description sql.NullString
	Price       sql.NullString
}
